#------------------------------------------------------------------------------#
# FleCSI Configuration for gitlab-ci Branch
#------------------------------------------------------------------------------#

stages:
  - test

test:
  stage: test
  script:
    echo "Success!"
